#!/usr/bin/env php
<?php
define('SUN_DEBUG', true);
require __DIR__ . '/vendor/autoload.php';

$config = require __DIR__ . '/config/console.php';
var_dump(2);exit;
$application = new Rxlisbest\Sun\Application($config);
$application->run();
