#!/usr/bin/env php
<?php
define('SUN_DEBUG', true);
require __DIR__ . '/vendor/autoload.php';

$config = require __DIR__ . '/config/console.php';
$application = new Rxlisbest\Sun\Console\Application($config);
$application->run();
